twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_canonical_base_url: '%app.canonical_base_url%'

when@test:
    twig:
        strict_variables: true
